"""Adaptar modelo Cliente a PostgreSQL

Revision ID: 08a038bcd1d4
Revises: 
Create Date: 2024-10-31 00:30:39.770246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a038bcd1d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca_moto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodo_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_credito',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('nomenclatura', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=False),
    sa.Column('numero_documento', sa.String(length=12), nullable=False),
    sa.Column('nombres', sa.String(length=255), nullable=False),
    sa.Column('apellidos', sa.String(length=255), nullable=False),
    sa.Column('celular', sa.String(length=10), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('barrio', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=50), nullable=True),
    sa.Column('departamento', sa.String(length=50), nullable=True),
    sa.Column('nombre_referencia_1', sa.String(length=100), nullable=True),
    sa.Column('celular_referencia_1', sa.String(length=10), nullable=True),
    sa.Column('nombre_referencia_2', sa.String(length=100), nullable=True),
    sa.Column('celular_referencia_2', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_documento'], ['tipo_documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linea_moto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_marca_moto', sa.Integer(), nullable=False),
    sa.Column('linea', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('url_imagen', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_marca_moto'], ['marca_moto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_tipo_credito', sa.Integer(), nullable=False),
    sa.Column('id_linea_moto', sa.Integer(), nullable=True),
    sa.Column('id_periodo_pago', sa.Integer(), nullable=False),
    sa.Column('valor_solicitud', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('numero_cuotas', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('valor_interes', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('valor_cuota_mensual', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('valor_cuota_periodo', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio_credito', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin_credito', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_periodo_pago'], ['periodo_pago.id'], ),
    sa.ForeignKeyConstraint(['id_tipo_credito'], ['tipo_credito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credito')
    op.drop_table('linea_moto')
    op.drop_table('clientes')
    op.drop_table('tipo_documento')
    op.drop_table('tipo_credito')
    op.drop_table('periodo_pago')
    op.drop_table('marca_moto')
    # ### end Alembic commands ###
