"""Create tables

Revision ID: 22e327ec09fa
Revises: c4096c99d12c
Create Date: 2024-10-22 09:32:06.200240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e327ec09fa'
down_revision = 'c4096c99d12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_periodo_pago', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_solicitud', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio_credito', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('credito', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'periodo_pago', ['id_periodo_pago'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credito', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('estado')
        batch_op.drop_column('credito')
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio_credito')
        batch_op.drop_column('fecha_solicitud')
        batch_op.drop_column('id_periodo_pago')

    # ### end Alembic commands ###
