"""Create marca_moto table

Revision ID: 282676252971
Revises: 9974a40db5b8
Create Date: 2024-10-21 08:27:23.182364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282676252971'
down_revision = '9974a40db5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca_moto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marca_moto')
    # ### end Alembic commands ###
