"""Create tables

Revision ID: 3d489dd1e65d
Revises: a843309b8d1b
Create Date: 2024-10-22 13:25:39.997189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d489dd1e65d'
down_revision = 'a843309b8d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_cuotas', sa.Numeric(precision=10, scale=0), nullable=False))
        batch_op.add_column(sa.Column('valor_cuota_mensual', sa.Numeric(precision=10, scale=0), nullable=False))
        batch_op.add_column(sa.Column('valor_cuota_periodo', sa.Numeric(precision=10, scale=0), nullable=False))
        batch_op.alter_column('valor_interes',
               existing_type=mysql.DECIMAL(precision=3, scale=2),
               type_=sa.Numeric(precision=10, scale=0),
               existing_nullable=False)
        batch_op.alter_column('fecha_solicitud',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.alter_column('fecha_inicio_credito',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('fecha_fin_credito',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_column('valor_cuota')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_cuota', mysql.DECIMAL(precision=10, scale=0), nullable=False))
        batch_op.alter_column('fecha_fin_credito',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('fecha_inicio_credito',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('fecha_solicitud',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
        batch_op.alter_column('valor_interes',
               existing_type=sa.Numeric(precision=10, scale=0),
               type_=mysql.DECIMAL(precision=3, scale=2),
               existing_nullable=False)
        batch_op.drop_column('valor_cuota_periodo')
        batch_op.drop_column('valor_cuota_mensual')
        batch_op.drop_column('numero_cuotas')

    # ### end Alembic commands ###
