"""Create tables

Revision ID: a843309b8d1b
Revises: 22e327ec09fa
Create Date: 2024-10-22 11:26:20.006699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a843309b8d1b'
down_revision = '22e327ec09fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_fin_credito', sa.DateTime(), nullable=False))
        batch_op.alter_column('valor_solicitud',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=0),
               existing_nullable=False)
        batch_op.alter_column('valor_interes',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=0),
               existing_nullable=False)
        batch_op.alter_column('valor_cuota',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=0),
               existing_nullable=False)
        batch_op.alter_column('valor_total',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=0),
               existing_nullable=False)
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('credito')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credito', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('fecha_fin', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('valor_total',
               existing_type=sa.Numeric(precision=10, scale=0),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('valor_cuota',
               existing_type=sa.Numeric(precision=10, scale=0),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('valor_interes',
               existing_type=sa.Numeric(precision=10, scale=0),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('valor_solicitud',
               existing_type=sa.Numeric(precision=10, scale=0),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('fecha_fin_credito')

    # ### end Alembic commands ###
