"""Create tables

Revision ID: c4096c99d12c
Revises: bbb508f4c4c3
Create Date: 2024-10-22 09:07:11.622130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4096c99d12c'
down_revision = 'bbb508f4c4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodo_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periodo_pago')
    # ### end Alembic commands ###
