"""Create tables

Revision ID: e9e5f92c5494
Revises: ecb3e96a2493
Create Date: 2024-10-21 09:49:04.321051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9e5f92c5494'
down_revision = 'ecb3e96a2493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_documento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('nomenclatura', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('linea_moto', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=mysql.INTEGER(display_width=10),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linea_moto', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=10),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    op.drop_table('tipo_documento')
    # ### end Alembic commands ###
