"""Create tables

Revision ID: ecb3e96a2493
Revises: 282676252971
Create Date: 2024-10-21 09:23:15.573783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb3e96a2493'
down_revision = '282676252971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linea_moto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_marca_moto', sa.Integer(), nullable=False),
    sa.Column('linea', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('url_imagen', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_marca_moto'], ['marca_moto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linea_moto')
    # ### end Alembic commands ###
